name: create-minions-bundle
description: Scaffold curated workflow bundles of MinionTypes, relations, and views
tier: prototype
lane: minions
priority: medium
oss: false
stack: [javascript]
repo: "https://github.com/mxn2020/create-minions-bundle"
deploy_url: null
last_active: 2026-02-25
tags: []
notes: 
